#ifndef ARRAY-SOUND_H
#define ARRAY-SOUND_H

#include "zero.h"
#include "uno.h"
#include "due.h"
#include "tre.h"
#include "quattro.h"
#include "cinque.h"
#include "sei.h"
#include "sette.h"
#include "otto.h"
#include "nove.h"
#include "dieci.h"
#include "undici.h"
#include "dodici.h"
#include "tredici.h"
#include "quattordici.h"
#include "quindici.h"
#include "sedici.h"
#include "diciassette.h"
#include "diciotto.h"
#include "diciannove.h"
#include "venti.h"
#include "trenta.h"
#include "quaranta.h"
#include "cinquanta.h"
#include "sessanta.h"
#include "settanta.h"
#include "ottanta.h"
#include "novanta.h"
#include "cento.h"
#include "mila.h"
#include "mille.h"
#include "milioni.h"
#include "milione.h"
#include "haifatto.h"
#include "haivinto.h"
#include "haiperso.h"
#include "passi.h"


#endif